use_frameworks!

target 'ECNetworking_Example' do

#  ECNetworkingOptions = { :git => 'git@github.com:EvanCooper9/ECNetworking.git' }
  ECNetworkingOptions = { :path => '../' }
  pod 'ECNetworking', ECNetworkingOptions

  target 'ECNetworking_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
