use_frameworks!

platform :ios, '11.0'

target 'ECNetworking_Example' do

#  ECNetworkingOptions = { :git => 'git@github.com:EvanCooper9/ECNetworking.git' }
  ECNetworkingOptions = { :path => '../' }
  pod 'ECNetworking', ECNetworkingOptions

  target 'ECNetworking_Tests' do
    inherit! :search_paths
  end
end
