name: Release

on:
  release:
    types:
      - published

jobs:
  release:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup environment
      run: echo 'RELEASE_VERSION='$(awk -F '/' '{print $NF}' <<< ${GITHUB_REF}) >> $GITHUB_ENV
      
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.POD_TRUNK_TOKEN }}
