name: Release

on:
  release:
    types:
      - published

jobs:
  release:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup environment
      run: |
        echo "GITHUB_REF: ${GITHUB_REF}
        echo "RELEASE_VERSION: $(awk -F '/' '{print $NF}' <<< ${GITHUB_REF})
      env:
        RELEASE_VERSION: $(awk -F '/' '{print $NF}' <<< ${GITHUB_REF})
      
    - name: Install Cocoapods
      run: gem install cocoapods
      
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        RELEASE_VERSION="$(awk -F '/' '{print $NF}' <<< ${GITHUB_REF})"
        pod lib lint --allow-warnings
        pod trunk push --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
