name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'Release type'
        required: true

jobs:
  release_job:
    runs-on: macos-latest
    steps:
    - name: deploy-ios-package
      uses: EvanCooper9/github-release-action@1.0.0
      with: 
        releaseType: ${{ github.event.inputs.releaseType }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}